on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  regenerate-labelsync:
    runs-on: ubuntu-latest
    steps:

      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/labelsync'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - uses: actions/checkout@v2
        if: steps.check.outputs.triggered == 'true'

      - run: 'yarn'
        if: steps.check.outputs.triggered == 'true'

      - run: 'yarn -s make && git add labelsync.yml'
        if: steps.check.outputs.triggered == 'true'
    
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.check.outputs.triggered == 'true'
        with:
          commit_message: Regenerate labelsync.yml
